// <auto-generated />
using GymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GymApp.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20180701150132_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymApp.Models.Exercise", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("category");

                    b.Property<string>("description");

                    b.Property<int>("language");

                    b.Property<string>("license_author");

                    b.Property<string>("name");

                    b.Property<string>("name_original");

                    b.Property<int>("status");

                    b.HasKey("id");

                    b.ToTable("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
